### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by nikkatalnikov** [joshkatz/r-script#19]
This simple code
```
var R = require("r-script");
var fs = require("fs");

var data = fs.readFileSync('r_code/sample.xlsx')
var out = R("r_code/sample.R")
  .data(data, 20)
  .callSync();
  
console.log(out);

```
leads to the following error
```
TypeError: Cannot read property 'data' of undefined
    at Object.<anonymous> (/Users/**/Desktop/**/**/r/index.js:9:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

what am i doing wrong?

**Comment by Khamurdik** [comment]
This bug can be solved with this pull request: https://github.com/joshkatz/r-script/pull/20

**Comment by MarkusKonk** [comment]
Hi,
I installed Rscript using your fork @Khamurdik as I had the same issue. However, now I get the following error. Do you not this issue? It occurs if I run an R script using `.call`
![error](https://user-images.githubusercontent.com/2863409/40425561-05e44210-5e99-11e8-8902-a05bdff70a19.jpg)

**Comment by garvk** [comment]
Hello,

I am having the same issue, has the issue been solved?

'r-script' package is running fine for me in one project, however, when i create the same project for a new user it gives me the error : "TypeError: Cannot read property 'data' of undefined". 

Is there a particular way how 'needs' package (on R) is to be installed and used for correct connection between nodejs and R ? 
Please, help!

**Comment by Codypinto23** [comment]
@Khamurdik and @MarkusKonk ,  I am also pulling the #20 request and receiving error:
```
TypeError: Incorrect value of args option
child_process.js:389
    at normalizeSpawnArguments (child_process.js:389:11)
    at Object.exports.spawn (child_process.js:496:38)
    at R.call (c:\Users\user\React\ExpressTest\express-test\node_modules\r-script\index.js:35:29)
    at executeBound (c:\Users\user\React\ExpressTest\express-test\node_modules\underscore\underscore.js:758:67)
    at R.<anonymous> (c:\Users\user\React\ExpressTest\express-test\node_modules\underscore\underscore.js:771:14)
    at R.call (c:\Users\user\React\ExpressTest\express-test\node_modules\underscore\underscore.js:122:29)
```

**Comment by MarkusKonk** [comment]
I created a very minimal working example which only runs the R file (and writes the out.Rout file) but does not pass data. For my purpose this was sufficient. Maybe it helps you: https://github.com/MarkusKonk/r-script

**Comment by Khamurdik** [comment]
Hi, i have modified a lot in my fork of that project with intentions to run
R code in Google Cloud Function. I have failed to do this and now my fork
('master' branch) is a complete mess. Sorry. if you really need that code
you can try to use 'fix_bindAll' branch only.

2018-05-23 15:56 GMT+03:00 Markus <notifications@github.com>:
